host: localhost:8888
info:
  contact: {}
  description: Acks 博客项目 API 接口文档
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: web接口bolg
  version: "1.0"
paths: {}
swagger: "2.0"
