# 服务配置
server:
  mode: "debug" # 运行模式 debug | release
  port: "8000" # 端口号
  keysign: "xyhOpen@666"

# 数据库配置
db: 
  host: "127.0.0.1" #主机地址
  user_name: "root" # 用户名
  password: "root" # 密码
  database: "ark" # 数据库名
  port: "3306" # 端口
  time_zone: "Local" # 时区
  max_idle_conn: 10 # 最大空闲连接数
  max_open_conn: 10 #最大打开连接数